# This file was auto-generated by Fern from our API Definition.

import datetime as dt


def serialize_datetime(v: dt.datetime) -> str:
    """
    Serialize a datetime including timezone info.

    Uses the timezone info provided if present, otherwise uses the current runtime's timezone info.

    UTC datetimes end in "Z" while all other timezones are represented as offset from UTC, e.g. +05:00.
    """
    if v.tzinfo is None:
        # Calculate local timezone once
        local_tz = dt.datetime.now().astimezone().tzinfo
        v = v.replace(tzinfo=local_tz)

    if v.tzinfo.tzname(None) == dt.timezone.utc.tzname(None):
        # UTC is a special case where we use "Z" at the end instead of "+00:00"
        return v.isoformat().replace("+00:00", "Z")
    else:
        # Typical +/- offset format
        return v.isoformat()
